apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rax-compute-gateway.fullname" . }}
  labels:
    {{- include "rax-compute-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.policy | nindent 4 }}
