apiVersion: v2
name: rax-compute-gateway
description: Open-source AI compute gateway
type: application
version: 0.2.0
appVersion: 0.2.0
kubeVersion: '>=1.30.0-0'
home: https://github.com/radium0090/Compute-Gateway
sources:
  - https://github.com/radium0090/Compute-Gateway
maintainers:
  - name: RAX Digital
    url: https://github.com/radium0090/Compute-Gateway
